let QuestList = [
  {
    title: 'Zabij smoka',
    description: 'Smok zaatakował naszą wikosę! Proszę pomóż nam! Odpowiedz 20 razy na pytania',
    progress: 0,
    goal: 30,
    type: 'ANWSER_QUEST',
    id: 0,
    reward: 4,
  },
  {
    title: 'Znajdź skarb w labiryncie',
    description: 'Podobno w labirycie jest ukryty skarb, może warto tam sie rozejrzeć!',
    progress: 0,
    goal: 20,
    type: 'COMPLETE_QUEST_LIST',
    id: 1,
    reward: 5,
  },
  {
    title: 'Uratuj smoka, zgładź księżniczkę!',
    description: 'Ten Biedny smok jest dręczony przez tą maszkarę! Ocal go',
    progress: 0,
    goal: 40,
    type: 'ANWSER_QUEST',
    id: 2,
    reward: 3,
  },
  {
    title: 'Dziki zgon!',
    description: 'Banda pijanych wikingów została u mnie w karczmie! Wygoń ich',
    progress: 0,
    goal: 25,
    type: 'COMPLETE_QUEST_LIST',
    id: 3,
    reward: 6,
  },
  {
    title: 'RST HACKATHON!!',
    description: 'KODUJ CAŁĄ NOC!',
    progress: 0,
    goal: 50,
    type: 'COMPLETE_QUEST_LIST',
    id: 4,
    reward: 6,
  },
  {
    title: 'Zostań pogromcą białego królika ludożercy! ',
    description:
      'Rycerze okrągłego stołu padli ofiarą królika ludożercy, znajdź święty granat ręczny i pokonaj go!',
    progress: 0,
    goal: 30,
    type: 'COMPLETE_QUEST_LIST',
    id: 5,
    reward: 6,
  },
  {
    title: 'ZJEDZ NAJWIEKSZĄ PIZZE ŚWIATA',
    description:
      'Żli włoscy mafiozi stworzyli największą pizze świata! Zjedz ją zanim jej pole grawitacyjne zniszczy ziemię!',
    progress: 0,
    goal: 25,
    type: 'COMPLETE_QUEST_LIST',
    id: 6,
    reward: 7,
  },
];
export default QuestList;
